config/routes.rb
Rails.application.routes.draw do
  root to: "todos#index"

  resources :todos, only: [:index, :create, :show, :edit, :update, :destroy] do
    post :toggle, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  acts_as_list scope: [:completed]

  validates :name, presence: true

  scope :by_position, -> { order(:position) }
  scope :completed, -> { where(completed: true) }
  scope :open, -> { where(completed: false) }

  def toggle_completed!
    toggle!(:completed)
    move_to_top if completed?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:edit, :update, :show, :toggle, :destroy]

  def index
    @new_todo = Todo.new
    @open_todos = Todo.open.by_position
    @completed_todos = Todo.completed.by_position
  end

  def create
    @todo = Todo.new(todo_params)

    unless @todo.save
      head :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      render "show"
    end
  end

  def show
  end

  def toggle
    @todo.toggle_completed!
  end

  def destroy
    @todo.destroy
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag :all, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= yield :head %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/todos/_todo.html.erb
<li id="<%= dom_id(todo) %>">
  <%= turbo_frame_tag todo, "frame" do %>
    <div class="todo-list__todo">
      <%= form_with model: todo, url: toggle_todo_path(todo), namespace: dom_id(todo), method: :post do |form| %>
        <%= form.check_box :completed, autocomplete: :off, data: { controller: "checkbox", action: "checkbox#submit" } %>

        <span class="todo-list__todo-name">
          <%= todo.name %>
        </span>
      <% end %>

      <% unless todo.completed? %>
        <span class="todo-list__todo-controls">
          <%= link_to "Edit", edit_todo_path(todo), class: "link" %> /
          <%= button_to "Delete", todo_path(todo), method: :delete, form: { class: :link, data: { turbo_confirm: "Are you sure?" } } %>
        </span>
      <% end %>
    </div>
  <% end %>
</li>

app/views/todos/create.turbo_stream.erb
<%= turbo_stream.append "todos", @todo %>

app/views/todos/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@todo) %>

app/views/todos/edit.html.erb
<%= turbo_frame_tag @todo, "frame" do %>
  <div class="todo-list__todo">
    <%= form_with model: @todo, namespace: "edit_#{@todo.id}", class: "form flex-grow" do |form| %>
      <div class="form__field">
        <%= form.text_field :name, data: { controller: "auto-select" }, class: "form__input", autocomplete: :off %>
      </div>

      <%= form.submit "Save", class: "button button--primary" %>
      <%= link_to "Cancel", todo_path(@todo), class: "button link" %>
    <% end %>
  </div>
<% end %>

app/views/todos/index.html.erb
<h1 class="title">Ajax to-dos</h1>

<%= form_with model: @new_todo, data: { controller: "form", action: "turbo:submit-end->form#reset" }, class: "form" do |form| %>
  <%= form.text_field :name, placeholder: "Add a new to-do...", autocomplete: :off, class: "form__input" %>
<% end %>

<ul class="todo-list todo-list--open-todos">
  <%= turbo_frame_tag "todos" do %>
    <%= render @open_todos %>
  <% end %>
</ul>

<ul class="todo-list todo-list--completed-todos">
  <%= turbo_frame_tag "completed_todos" do %>
    <%= render @completed_todos %>
  <% end %>
</ul>

app/views/todos/show.html.erb
<%= render "todo", todo: @todo %>

app/views/todos/toggle.turbo_stream.erb
<%= turbo_stream.remove dom_id(@todo) %>

<% if @todo.completed? %>
  <%= turbo_stream.prepend "completed_todos", @todo %>
<% else %>
  <%= turbo_stream.append "todos", @todo %>
<% end %>